---
machines:
  spa_web:
    hostname: "spa_web"
    ipv4: "192.168.69.10"
    playbook: "provisioning/ansible/web_server.yml"
    folder_map:
    - guest: "/opt/www"
      host: "../../byng_systems@bitbucket.org/spark-api/"
      owner: www-data
      group: www-data
    port_map:
    - guest: 80
      host: 8080
    - guest: 443
      host: 4443

  spa_db:
    hostname: "spa_db"
    ipv4: "192.168.69.20"
    playbook: "provisioning/ansible/db_server.yml"
